config/routes.rb
OrganicShop2::Application.routes.draw do
  get "admin" => 'admin#index'

  resources :orders

  resources :line_items, :carts,   :products, :users,   :sessions

    get "admin/index"

  get "welcome/thank_you"

 match '/your_cart' => "carts#your_cart", :as => "your_cart"
 match '/login' => "sessions#new", :as => "login"
match '/logout' => "sessions#destroy", :as => "logout"

  match 'users/:id'=>'users#edit'

  root :to => 'welcome#home', as: 'home'

end

app/models/user.rb
require 'digest'
class User < ActiveRecord::Base

  has_many :products
#@reference wesley gorman laptop_shop 2 tutorial,step 27
  def self.authenticate(email, password)
    user = find_by_email(email)
    return user if user && user.authenticated?(password)
  end
 #@reference wesley gorman,laptop_shop 5 tutorial,step 7
  def authenticated?(password)
    self.hashed_password == encrypt(password   + "ruby_rocks" + self.salt)
  end

#@reference wesley gorman,laptop_shop 2,tutorial, step 25
  attr_accessor :password
  before_save :encrypt_password
  protected
  def encrypt_password
    return if password.blank?
    #@reference wesley gorman,laptop_shop 5 tutorial, step6
    salt = generate_salt
    self.hashed_password = encrypt( password + "ruby_rocks" + salt)
  end

  def encrypt(string)
    Digest::SHA1.hexdigest(string)
  end

#@reference wesley gorman laptop_shop 2, step 44
  validates :email,
            :uniqueness => true,
            :length => {:within => 5..30},
            :format => {:with =>
                            /^[^@][\w.-]+@[\w.-]+[.][a-z]{2,4}$/i}
  validates :password,
            :confirmation => true,
            :length => {:within => 4..20},
            :presence => true

   validates_presence_of :forename, :surname,:town, :occupation

end

 #@reference wesley gorman,laptop_shop 5 tutorial, step5
def generate_salt
  chars = ("a".."z").to_a + ("A".."Z").to_a + ("0".."9").to_a
  salt = ""
  1.upto(10) { |i| salt << chars[rand(chars.size-1)] }
  self.salt = salt
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
#before_filter :authenticate, :only => [:index, :edit, :update]


 def update
     @user=User.find(params[id])
    @user.update_attributes(params[:user])
           flash[:notice] = " "

           redirect_to(@user,:notice => 'updated')

     end

   def new
    @user= User.new

  end


  def show
 @user=User.find(params[:id])

  end

  def index
      @users = User.find(:all)

    end

 def edit
   @user = User.find(params[:id])
 end



 	def destroy
         @user = User.find(params[:id])
         @user.destroy
         flash[:notice] = "User deleted"
         redirect_to users_path
       end




#@ reference wesley gorman,laptop_shop 2 tutorial, step 12

   def create
@user = User.new(params[:user])
if @user.save
redirect_to products_path, :notice => 'User creation successful!, dont forget to login'
else
render :action => 'new'
end
    end
  end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
 <h1>Edit Details</h1>

<% form_for(@user) do |f| %>
  <p>
    <%= f.label :forename %>:
    <%= f.text_field :forename %>
  </p>
  <p>
    <%= f.label :surname %>:
    <%= f.text_field :surname %>
  </p>

    <%= f.label :email %>:
    <%= f.text_field :email %>
  </p>


    <%= f.label :password %>:
    <%= f.text_field :password %>
  </p>

  <p>
    <%= f.submit "Update" %>
  </p>

<% end %>

 <%= link_to 'Back', products_path %>

app/views/users/form.html.erb
<h1>Sign Up</h1>





 <% form_for(@user) do |f| %>
 <% if @user.errors.any? %>
 <div id="errorExplanation">
 <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
 <ul>
 <% @user.errors.full_messages.each do |msg| %>
 <li><%= msg %></li>
 <% end %>
 </ul>
 </div>
 <% end %>



  <div class="field">
 <%= f.label :email %><br />
 <%= f.text_field :email %>
 </div>
 <div class="field">
 <%= f.label :password %><br />
 <%= f.password_field :password %>
 </div>
 <div class="actions">
 <%= f.submit "Create User"%>
 </div>
 <% end %>
 <%= link_to 'Back', products_path %>

app/views/users/index.html.erb
<h1>Listing Users</h1>

<table>
  <tr>
    <th>Email</th>
    <th>Admin</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.email %></td>
    <td><%= user.admin %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
   <h1>Sign Up</h1>





<% form_for(@user) do |f| %>
<% if @user.errors.any? %>
<div id="errorExplanation">
<h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
<ul>
<% @user.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
</div>
<% end %>



 <div class="field">
     <% if flash[:alert] %>
<p id="notice"><%= flash[:alert] %></p>
       <%end %>
<%= f.label :email %><br />
<%= f.text_field :email %>
</div>
<div class="field">
<%= f.label :password %><br />
<%= f.password_field :password %>
</div>
<div class="field">

  <%= f.label :forename %>: <br/>
  <%= f.text_field :forename %>

</div>
 <div class="field" >

  <%= f.label :surname %>:   <br/>
  <%= f.text_field :surname %>

</div>
 <div class="field" >

  <%= f.label :occupation %>:   <br/>
  <%= f.text_field :occupation %>

</div>

   <div class="field" >

  <%= f.label :town %>:   <br/>
  <%= f.text_field :town %>

</div>


<div class="actions">
<%= f.submit "Create User"%>
</div>

<% end %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>password:</b>
  <%= @user.hashed_password%>
</p>


<p><b>Forname</b>
<%= @user.forename%>
 </p>

 <p><b>Surname</b>
   <%= @user.surname%>
 </p>
 <p><b>Occupation</b>
   <%= @user.occupation%>
 </p>

   <p><b>Town</b>
   <%= @user.town%>
 </p>

 <p>
<b>Admin</b>
<%= @user.admin %>
   </p>
  <p>  <b>User Id</b>
    <%= @user.id%>


  </p>


<%= link_to 'Back', users_path %>

  <%= link_to 'edt', user_path%>