config/routes.rb
OrganicShop2::Application.routes.draw do
  get "admin" => 'admin#index'

  resources :orders

  resources :line_items, :carts,   :products, :users,   :sessions

    get "admin/index"

  get "welcome/thank_you"

 match '/your_cart' => "carts#your_cart", :as => "your_cart"
 match '/login' => "sessions#new", :as => "login"
match '/logout' => "sessions#destroy", :as => "logout"

  match 'users/:id'=>'users#edit'

  root :to => 'welcome#home', as: 'home'

end

app/models/cart.rb
class Cart < ActiveRecord::Base

  has_many :line_items, dependent: :destroy






  #@reference wesley gorman laptop_shop 3 tutorial step 29
  def add_product(product)
    current_item = line_items.where(:product_id => product.id).first
    if current_item
      current_item.quantity += 1
    else
      current_item = LineItem.new(:product_id => product.id)
      line_items << current_item
    end
    current_item
  end
#@reference wesley gorman laptop_shop 3 tutorial,step2
   def total_price
total = 0
line_items.each do |line_item|
total += line_item.product.price * line_item.quantity
end
total

  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  # GET /carts
  # GET /carts.xml
  def index
    @carts = Cart.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @carts }
    end
  end

  # GET /carts/1
  # GET /carts/1.xml
  def show
    begin
    @cart = Cart.find(params[:id])
    #@reference sam ruby, dave thomas, david heinemeier hanson, agile web development,page121, chapter 10 , fourth edition
    rescue ActiveRecord::RecordNotFound
      logger.error"invalid cart access#{params[:id]}"

      redirect_to products_url,notice:'invalid cart id'
      else

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @cart }
    end
    end
     end

  # GET /carts/new
  # GET /carts/new.xml
  def new
    @cart = Cart.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @cart }
    end
  end

  # GET /carts/1/edit
  def edit
    @cart = Cart.find(params[:id])
  end

  # POST /carts
  # POST /carts.xml
  def create
    @cart = Cart.new(params[:cart])

    respond_to do |format|
      if @cart.save
        format.html { redirect_to(@cart, :notice => 'Cart was successfully created.') }
        format.xml  { render :xml => @cart, :status => :created, :location => @cart }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @cart.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /carts/1
  # PUT /carts/1.xml
  def update
    @cart = Cart.find(params[:id])

    respond_to do |format|
      if @cart.update_attributes(params[:cart])
        format.html { redirect_to(@cart, :notice => 'Cart was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @cart.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.xml

#@reference sam ruby, dave thomas, david heinemeier hanson, agile web development,page124, chapter 10 , fourth edition

  def destroy
    @cart = current_cart
    @cart.destroy
    #@reference wesley gorman, laptop_shop 4 tutorial, step 7
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to products_url,notice:'your cart is now empty' }
      format.xml  { head :ok }
    end
  end
  #@reference wesley gorman,laptop_shop 3 tutorial, step18
  def your_cart
    redirect_to :action => "show", :id=> current_cart.id

  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>
<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @carts.each do |cart| %>
  <tr>
    <td><%= link_to 'Show', cart %></td>
    <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
    <td><%= link_to 'Destroy', cart, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
  <% if notice %>
<p id="notice"><%= notice %></p>
  <%end%>

<div align="center">

<h2>Cart</h2>
<ul>

 <% for item in @cart.line_items %>
  <li><%= item.quantity%>&times; <%= item.product.name%></li>
  <% end %>

  <br />

     Total Price: <%= number_to_currency( @cart.total_price, :unit => '&euro;') %><br/>
  <br />
  <br />
  <%=button_to 'delete cart', @cart,:method => :delete, :confirm => 'are you sure?'%>
  <br/>


  <%= button_to "Checkout", new_order_path, method: :get %>
</ul>

<br />
<%= link_to 'continue shopping', products_path %>     <%= link_to "Checkout", new_order_path, method: :get %>

 </div>