config/routes.rb
OrganicShop2::Application.routes.draw do
  get "admin" => 'admin#index'

  resources :orders

  resources :line_items, :carts,   :products, :users,   :sessions

    get "admin/index"

  get "welcome/thank_you"

 match '/your_cart' => "carts#your_cart", :as => "your_cart"
 match '/login' => "sessions#new", :as => "login"
match '/logout' => "sessions#destroy", :as => "logout"

  match 'users/:id'=>'users#edit'

  root :to => 'welcome#home', as: 'home'

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :user
 has_many :line_items

 # @reference sam ruby, dave thomas, david heinemeier hanson, agile web development,chapter 7, page80
 validates :name, :description, :image_url, presence: true
validates :price, numericality: {greater_than_or_equal_to: 0.01}
validates :name, uniqueness: true
 validates_length_of :name, :minimum => 3
  validates :image_url, allow_blank: true, format: {
with: %r{\.(gif|jpg|png)$}i,
message: 'must be a URL for GIF, JPG or PNG image.'
}
  # @reference wesley gorman,laptop_shop 4 tutorial, step 20
  attr_accessible :name, :description, :price ,:image_url

# @reference wesley gorman,laptop_shop 1 tutorial,step 17
def self.search(search_query)
if search_query
find(:all,:conditions => ['name LIKE ?', "%#{ search_query}%"])
else
find(:all)
end
end

end

#   #has_many :orders, through: :line_items

app/controllers/products_controller.rb
class ProductsController < ApplicationController
before_filter :authenticate, :except => [:index,:show,]

  # GET /products
  # GET /products.xml
  def index
   @products = Product.search(params[:search_query])

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @products }
    end
  end

  # GET /products/1
  # GET /products/1.xml
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @product }
    end

  end

  # GET /products/new
  # GET /products/new.xml
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @product }
    end
  end


  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.xml
  def create
    #@reference wesley gorman, laptop_shop 2 tutorial, step 41
     @product = current_user.products.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to(@product, :notice => 'Product was successfully created.') }
        format.xml  { render :xml => @product, :status => :created, :location => @product }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.xml
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to(@product, :notice => 'Product was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.xml
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to(products_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>
<h1> products catalogue</h1>
 <div id="search" align="right" >
<% form_tag products_path, :method => 'get' do %>
    <p>
      <%= text_field_tag :search_query, params[:search_query] %>
      <%= submit_tag "Search", :name => nil %>
    </p>   </div>
<% end %>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Image url</th>
    <th>Price</th>
    <th>UserID</th>
    <th></th>
    <th></th>
  </tr>

  <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= image_tag(product.image_url, class: 'list_image') %></td>
        <td><%= product.price %></td>

           <td><%= product.user_id %></td>
        <td> <%= button_to 'Add to Cart', line_items_path(product_id: product) %> </td>
         <% if current_user.admin %>
        <td><%= link_to 'Show', product %></td>

        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, :confirm => 'Are you sure?', :method => :delete %></td>
         <% end %>
      </tr>
  <% end %>
</table>

<br/>
  <% if current_user.admin %>
<%= link_to 'New Product', new_product_path %>
 <%end%>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @product.name %>
    <%= auto_link @product.description %>
</p>

<p>

  <b>Description:</b>
  <%= @product.description %>
</p>

<p>
  <b>Image url:</b>
  <%= @product.image_url %>
</p>

<p>
  <b>Price:</b>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>